// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnjrjnidtubvcicudscz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuanJqbmlkdHVidmNpY3Vkc2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNzEyODcsImV4cCI6MjA1NzY0NzI4N30.p6qPzrPQf_rrS_9vKoxFQlL7F8vy6FsdmjWE9mH_Vx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);